sudo: required
dist: trusty
language: generic
cache: apt
env:
  global:
    - ROS_DISTRO=indigo
    - NUM_OF_PACKAGES=5
  matrix:
    - CATKIN_CONFIG="--merge-devel"
    - CATKIN_CONFIG="--isolate-devel"
# Install system dependencies, namely ROS.
before_install:
  # Define some config vars.
  - export ROS_CI_DESKTOP=`lsb_release -cs`  # e.g. [precise|trusty]
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  # Install ROS
  - sudo sh -c "echo \"deb http://packages.ros.org/ros-shadow-fixed/ubuntu $ROS_CI_DESKTOP main\" > /etc/apt/sources.list.d/ros-latest.list"
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  # Install ROS
  - sudo apt-get install -y python-catkin-pkg python-catkin-tools python-rosdep python-wstool ros-$ROS_DISTRO-catkin
  - sudo apt-get install -y ros-$ROS_DISTRO-rosbash ros-$ROS_DISTRO-rospack
  - sudo apt-get install -y ros-$ROS_DISTRO-ros-core
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - env | grep ROS
  - rospack profile
  # Setup for rosdep
  - sudo rosdep init
  - rosdep update

# Create a catkin workspace with the package under test.
install:
  - sudo apt-get install -y pwgen

script:
  - rosversion catkin
  # set up workspace
  - mkdir -p catkin_ws/src
  - cd catkin_ws/src
  - rm -fr test-*
  - for i in $(seq 1 ${NUM_OF_PACKAGES}); do catkin_create_pkg test-`pwgen 13 1`-$i; done
  - cd ..
  # run build
  - rm -fr build devel .catkin_tools
  - catkin init
  - catkin config ${CATKIN_CONFIG}
  - catkin config --merge-devel
  - catkin b -v -i -p 4
  # check ROS_PAKCAGE_PATH
  - cat devel/.catkin
  - source devel/setup.bash
  - rospack list | grep catkin_ws
  - export NUM=`sed 's/[^;]//g' devel/.catkin | wc -c`
  - NUM=$((NUM + 1))
  - if [ $NUM != ${NUM_OF_PACKAGES} ] ; then exit 1; fi

  